// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/home/um/sourcecode/my/um-multimedia-manager/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
